version: '3'
services:
  grafana:
    hostname: grafana
    image: grafana/grafana:7.5.6
    environment:
      # - GF_INSTALL_PLUGINS="grafana-clock-panel,grafana-simple-json-datasource"
      # - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      # - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - /volume/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    user: "$UID:$GID"
    networks:
      - net-monitor
    deploy:
      placement:
        constraints:
          - node.hostname == slave4

  
  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.27.1
    ports:
      - 9090:9090
    user: "$UID:$GID"
    networks:
      - net-monitor
    depends_on:
      - cadvisor 
    volumes:
      - /volume/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /volume/prometheus/data:/prometheus
    deploy:
      placement:
        constraints:
          - node.hostname == slave4
  
  node-exporter:
    hostname: node-exporter
    image: prom/node-exporter:v1.1.2
    # command:
    # - --path.procfs=/host/proc
    # - --path.sysfs=/host/sys
    ports:
      - 9100:9100
    networks:
      - net-monitor
    deploy:
      mode: global


  cadvisor:
    hostname: cadvisor
    image: google/cadvisor:v0.33.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    networks:
      - net-monitor
    deploy:
      mode: global


networks:
  net-monitor:
    driver: overlay