
  - name: restart_zabbix_services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    become: true
    loop:
      - mariadb
      - nginx
      - php8.1-fpm
      - zabbix-server
      - zabbix-agent
