version: '3.8'
services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    hostname: elasticsearch01
    environment:
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch02,elasticsearch03
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearch01
      - xpack.security.enabled=false
      - node.ml=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - transport.publish_host=elasticsearch01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
            - node.hostname == slave2
    networks:
        - sepehr-net 
    ports:
      - "9200:9200"

    volumes:
      - esdata01:/usr/share/elasticsearch/data


  elasticsearch02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    hostname: elasticsearch02
    environment:
      - "cluster.name=docker-cluster"
      - discovery.seed_hosts=elasticsearch01,elasticsearch03
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearch02
      - xpack.security.enabled=false
      - node.ml=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - transport.publish_host=elasticsearch02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
            - node.hostname == slave2
    networks:
        - sepehr-net 
    volumes:
      - esdata02:/usr/share/elasticsearch/data


  elasticsearch03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    hostname: elasticsearch03
    environment:
      - "cluster.name=docker-cluster"
      - discovery.seed_hosts=elasticsearch01,elasticsearch02
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearch03
      - xpack.security.enabled=false
      - node.ml=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - transport.publish_host=elasticsearch03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
            - node.hostname == slave2
    networks:
        - sepehr-net 
    volumes:
      - esdata03:/usr/share/elasticsearch/data

networks:
  sepehr-net:
    external: true
    name: sepehr 

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local