
- name: Generic Config
  ini_file:
    dest: /etc/zabbix/zabbix_agent2.conf
    section: 
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: ListenPort, value: "{{ zabbix_port }}" }
    - { option: ServerActive, value: "{{ zabbix_server_ip }}" }
    - { option: Server, value: "{{ zabbix_server_ip }}" }
    - { option: Hostname, value: "" }
    - { option: HostnameItem, value: "system.hostname[shorthost]" }      
    - { option: Timeout, value: "{{ zabbix_timeout }}" }
    - { option: HostMetadataItem, value: "system.run[/etc/zabbix/scripts/discovery.sh]" }
    - { option: AllowKey, value: "system.run[*]" }
  notify: 
    - restart zabbix