---
- name: install postgres in ubuntu
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: 
    - postgresql
    - postgresql-contrib
    - python3-psycopg2
  notify: start_postgres
  when: ansible_distribution == "Ubuntu"